//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_Principal : DbContext
    {
        public Entities_Principal()
            : base("name=Entities_Principal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Suspects> Suspects { get; set; }
        public virtual DbSet<Weapons> Weapons { get; set; }
    
        public virtual int sp_Places_RND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Places_RND");
        }
    
        public virtual ObjectResult<sp_Random_Result> sp_Random()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Random_Result>("sp_Random");
        }
    
        public virtual int sp_Suspects_RND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Suspects_RND");
        }
    
        public virtual int sp_Weapons_RND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Weapons_RND");
        }
    }
}
